travis:
  secure:
    BINSTAR_TOKEN: W5G7sc722W01543n3teH8sdZcFsuA7MYotql+DA7mu65QkoUA0xT6H1Zq0lx/O6xtSKOBgKP51Kt/slFCmXR7Zivj/hbr4nWwZN9Fo2k9RulCIMjXGPHQWIc3gA/4kIcQPzIxCGF4QpC03P9SU5SoA0Cg5kNf0/wSjzHvaq1jBtT7MNJa6O/53PZ76zKiC0f8LeQNzCyhkPTdTHzFf8RoHT0mv/hI+Hih60OSCsYyKNpjQAWEMnKI7OCkc0EPaU7ynz/QLXAbSR/e2jBqpiD7BeqRFTIUa6y75mygI6DFlC2ivQXz6DiY8o7t/Xt/BnaL81cCIbBYGSnU7Zom6RXGnTuS6eLDUDOI1m+8hkN3w0/7tuh+lvw3bRLDudCnvj+qB5yszu++/og4cIyO/s63OJaOw1zZO1EQ4QbYqVmUP35TtOF+/OBIcIiIgFfhoYB77DNM4up46dXAj/ZZAiD8Rjq58/Kl9lmW55oNp/oPldAAzi1712NhllQ4y5uaBEGe0mOzLhuRdzuf42QF0E8J0bM5unncnKtbRj0O2Bg1nnyG68izMfJYKX5DOL9xvtBmATa82vYWGARhssFlMn0i3xOEG0dHMy9VQRntAf+jHcCtwyeNi/AHfUCEPeD9t474iDsSIlYIb48xWxhX2dCoypcV62nZpA9IcF2HP9kM0Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
