travis:
  secure:
    BINSTAR_TOKEN: cfNp4tRZrbF9ZlGBPZKCQwQ9f4BBvvXo5rWpfRt4X163iiTaBuQqaKMf5fZB4LZUZICOv3U7n2r5E/2pRdfP79nNsVoH8TKmRyo/EOnCxCf0O5P0HlvmZqODBDSdAmKDao6Hh7Qktj9ZZlAwYG9E+Sf2KxCqDT9WeTQjL/oOg3pTSDQgIpJSdOBLy+9kOpe+Y+DQYezHhTFp3Wafv4Tgxl6BdZCONMb0ORwrI4pHIPXuiuJfS50u/JrEoHdqUuHShFmwYMN4u/pJpnBTYZpwTwLKKvUZgJRIHwzqP0Urlbs+7rfQdh9t3YtxnFW31lbkj66oYS61BvfuIr5d0KFp5u4U7IZqoblY33ewM4sxQ+2QjCkPhsECh3JqcW75vFYHw9l6ZLYfJ7eQC9Yj6OFSteeDZwecvU6/FqVWFDxc4W8jrmEIYq4M65CkoF11qucdKafwn+4fjWuH7numQ3AP7TcURnxcs7BPrBoWWJBV141P2es+kxX8wFZ19xOqkQvA1HN5jcO+j6V3BEdQm1ItpgzWDKyVAb+Tt5Dc9mdcsV+B4Boy1LDbfSBVii8pIwktbjC5anB3DTXTP/vn/Y34dDZMDkRuA4JK3HlHYcZ6erj5T0RURHhoTrq+4l49SOZAREmOZ5gzONcaZp65xSBWQXJ7X5mIGnQRRJ8alQJ4US8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
